#
# Network UPS Tools: AppVeyor CI build recipe: NUT for Windows with MSYS2/MinGW x64
#
# https://www.msys2.org/docs/ci/
# https://www.appveyor.com/docs/appveyor-yml/
# https://www.appveyor.com/docs/build-configuration/
# https://www.appveyor.com/docs/windows-images-software/

version: 2.8.0.{build}-{branch}

# base image
image: Visual Studio 2022

# branches to build
branches:
  # whitelist
  only:
    - master
    - /Windows/

platform: x64

# https://github.com/networkupstools/nut/blob/Windows-v2.8.0-1/docs/config-prereqs.txt#L951
install:
  - ps: |
        $ErrorActionPreference = 'Continue' # stderr not fatal
        $ErrorAction = 'Continue' # stderr not fatal
        C:\msys64\usr\bin\bash -lc "mkdir -p /var/cache/pacman/pkg" 2>&1 | %{ "$_" }
  - ps: |
        $ErrorActionPreference = 'Continue' # stderr not fatal
        $ErrorAction = 'Continue' # stderr not fatal
        C:\msys64\usr\bin\bash -lc "date -u; pacman --noconfirm -Syuu" 2>&1 | %{ "$_" } # Core update (in case any core packages are outdated)
  - ps: |
        $ErrorActionPreference = 'Continue' # stderr not fatal
        $ErrorAction = 'Continue' # stderr not fatal
        C:\msys64\usr\bin\bash -lc "date -u; pacman --noconfirm -Syuu" 2>&1 | %{ "$_" } # Normal update
  - ps: |
        $ErrorActionPreference = 'Continue' # stderr not fatal
        $ErrorAction = 'Continue' # stderr not fatal
        C:\msys64\usr\bin\bash -lc "date -u; pacman --noconfirm -S --needed base-devel mingw-w64-x86_64-toolchain autoconf-wrapper automake-wrapper libtool mingw-w64-x86_64-libltdl gcc ccache mingw-w64-x86_64-ccache git aspell aspell-en python mingw-w64-x86_64-python-pygments mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-libusb mingw-w64-x86_64-libusb-compat-git mingw-w64-x86_64-neon libneon-devel mingw-w64-x86_64-libmodbus-git mingw-w64-x86_64-libgd"2>&1 | %{ "$_" }
  - ps: |
        $ErrorActionPreference = 'Continue' # stderr not fatal
        $ErrorAction = 'Continue' # stderr not fatal
        C:\msys64\usr\bin\bash -lc "date -u; du -ks / ; date -u; du -ks /var/cache/pacman/pkg; date" 2>&1 | %{ "$_" }


build_script:
  - ps: |
        $ErrorActionPreference = 'Continue' # stderr not fatal
        $env:CHERE_INVOKING = 'yes'  # Preserve the current working directory
        $env:MSYSTEM = 'MINGW64'  # Start a 64 bit Mingw environment
        C:\msys64\usr\bin\bash -lc 'PATH="/mingw64/bin:$PATH" ./ci_build.sh' 2>&1 | %{ "$_" }

cache:
  - C:\msys64\var\cache\pacman\pkg # -> appveyor.yml
  - C:\msys64\home\%USER\.ccache

